


export enum APIENUM {
  ASS = 'asset',
  SVP='survey/feedbackbyperiod',
  CON = 'contact',
  COM = 'company',
  CAT = 'category',
  DEPT = 'department',
  DES = 'designation',
  LOC = 'location',
  LOGIN = 'login.php',
  LEAVETYPE = 'leavetype',
  USERLEAVETYPE = '/leave/leavetype.php',
  INCR = 'incrementpromotion',
  MENU = 'menu',
  LEAVE = 'leave',
  SQ = 'surveyquestion',
  SQR='survey/readbyperiod',
  MENUG = 'menugroup',
  train = 'training',
  trainpending = 'training/pendingapprove.php',
  extra = 'extra',
  ROLE = 'role',
  MROLE = 'mrole',
  EXP = 'expense',
  LOG = 'login',
  LON = 'loan',
  EMP = 'employee',
  SD='survey/readdepartment.php',
  HOL = 'holiday',
  SAG = 'salarygroup',
  FILE = 'Fileuploads/fileupload.php',
  APPROVELOAN = 'loan/populateapprove.php',
  LOANEMPLOYEE = 'loan/employeeread',
  LOANTIMELINE = "loan/timelineread.php",
  LEAVEREPORT = 'leave/reporttoreaad.php',
  LEAVEAPPROVE = 'leave/approve.php',
  LEAVEAVAILABLE = 'leave/availableleavedays.php',
  TRAINAPPROVE = 'training',
  PAYROLL = 'salaryslip',
  POPULATEPAYROLL = 'salaryslip/populatepayroll.php',
  CREATEPAYROLL = '/salaryslip/create.php',
  EVENT = 'event',
  RT = 'surveyrating',
  SS='survey',
  PAYROLLM = 'salaryslip',
  WORKFLOWSETUP = 'workflowsetup',
  LOANWORKFLOWSETUP = 'loanworkflowsetup',
  CHECK = 'salaryslip/checkmonth.php',
  ST = "ST"
}

export enum UType{
    CERT,
    AVATAR,
    DRIVER,
    PAN,
    VoterID,
   SSN,
   Offer,
   Joining ,
   Contract,
   Resume,
   Relieving,
   Experience

}
