

export enum APIENUM{
    ASS='asset',
    CON='contact',
    COM='company',
    CAT='category',
    DEPT='department',
    DES='designation',
    LOC='location',
    LOGIN='login.php',
    LEAVETYPE='leavetype',
    INCR='incrementpromotion',
    MENU='menu',
    LEAVE='leave',
    MENUG='menugroup',
    train='training',
    trainpending='training/pendingapprove.php',
    extra='extra',
    ROLE='role',
    MROLE='mrole',
    EXP='expense',
    LOG='login',
    LON='loan',
    EMP='employee',
    SAG='salarygroup',
    FILE='Fileuploads/fileupload.php',
    APPROVELOAN='loan/populateapprove.php',
    LOANEMPLOYEE='loan/employeeread',
    LOANTIMELINE="loan/timelineread.php",
    LEAVEREPORT='leave/reporttoreaad.php',
    LEAVEAPPROVE='leave/approve.php',
    TRAINAPPROVE='training',
    PAYROLL='salaryslip',
    POPULATEPAYROLL='salaryslip/populatepayroll.php',
    CREATEPAYROLL='/salaryslip/create.php',
    EVENT='event',
    PAYROLLM='salaryslip',
    WORKFLOWSETUP='workflowsetup',
    LOANWORKFLOWSETUP='loanworkflowsetup',
    CHECK='salaryslip/checkmonth.php'
}

export enum UType{
    CERT,
    AVATAR,
    DRIVER,
    PAN,
    VoterID,
   SSN,
   Offer,
   Joining ,
   Contract,
   Resume,
   Relieving,
   Experience

}
